hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
spring.cloud.loadbalancer.retry.enabled: true
ribbon.ReadTimeout: 10000
ribbon.ConnectTimeout: 10000
hystrix.threadpool.default.coreSize: 200
hystrix.threadpool.default.maximumSize: 200

mybatis.mapperLocations: "classpath*:/orm/*.xml"
pagehelper.helper-dialect: "mysql"
pagehelper.params: "count=countSql"
pagehelper.reasonable: false
pagehelper.support-methods-arguments: true
mapper.identity: "MYSQL"
spring.datasource.driver-class-name: "com.mysql.jdbc.Driver"
spring.datasource.initialSize: 1
spring.datasource.maxActive: 10
spring.datasource.maxWait: 2000
spring.datasource.minIdle: 1
spring.datasource.type: "com.alibaba.druid.pool.DruidDataSource"
spring.datasource.username: "devdb"
spring.datasource.password: "7yZFohkv"

spring.cloud.consul.discovery.enabled: true
spring.cloud.consul.discovery.healthCheckInterval: 10s
spring.cloud.consul.discovery.instanceId: "${spring.application.name}:${spring.cloud.consul.discovery.hostname}:${server.port}"
spring.cloud.consul.enabled: true
spring.cloud.consul.host: 10.200.110.3
spring.cloud.consul.port: 8500

spring.zipkin.base-url: "http://10.200.110.3:9411"
server.undertow.io-threads: 4
server.undertow.worker-threads: 200